version: "3.8"

services:
  nodejs:
    build:
      context: .
    container_name: nodejs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: tail -f /dev/null

volumes:
  node_modules:
