version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nodejs
      MYSQL_DATABASE: nodejs
      MYSQL_USER: nodejs
      MYSQL_PASSWORD: nodejs

  nodejs:
    build:
      context: .
    container_name: nodejs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: tail -f /dev/null
    depends_on: 
      - db

volumes:
  db_data:
  node_modules:
